CREATE TABLE users (
  "id" BIGSERIAL PRIMARY KEY,
  "createdAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL,
  "firstName" VARCHAR(255) NOT NULL,
  "lastName" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL UNIQUE
);